### ISSUE TITLE
[Refactor] [UI/UX] Refactor Clinical Site pages merged from HCO SSApp part 2 to use only webcardinal features instead of old cardinal framework

### ISSUE THREAD

**Issue by paiusCatalin** [PharmaLedger-IMI/iot-pmed-workspace#108]
Following the guidelines presented within issues #76 - #101, refactor the following pages from Clinical Site SSApp under `/code/pages/econsent `directory:

- trial-management.html
- trial-participant.html
- trial-participant-details.html
- trial-participants.html
- visit-details-procedures.html
- visit-edit.html
- visits.html
- visits-procedures.html

![image](https://user-images.githubusercontent.com/17168446/143609282-1cee5015-a42a-4d10-adc4-14f64135b556.png)
Mock-up: https://www.figma.com/file/CmwZYstqv2idRwREtOuQDv/eConsent-HCO?node-id=0%3A1

For the design path, in the current state, each HTML file is importing some CSS file(s) from `/code/assets/css`. Extract only the needed CSS rules that might be useful for the page(s).

**Comment by Mastaleru** [comment]
cardinal components removal finished. still, some particular css should be extracted.
