### ISSUE TITLE
[Refactor] [UI/UX] Refactor Clinical Site modals merged from HCO SSApp part 1 to use only webcardinal features instead of old cardinal framework

### ISSUE THREAD

**Issue by paiusCatalin** [PharmaLedger-IMI/iot-pmed-workspace#109]
Following the guidelines presented within issues #76 - #101, refactor the following pages from Clinical Site SSApp under `/code/modals` directory:
confirmation-alert.html
edit-recruitment-period.html
set-procedure-date.html
![image](https://user-images.githubusercontent.com/17168446/143609700-2d86d360-1369-4427-96f7-0227320ff998.png)
Mock-up: https://www.figma.com/file/CmwZYstqv2idRwREtOuQDv/eConsent-HCO?node-id=0%3A1

For the design path, in the current state, each HTML file is importing some CSS file(s) from `/code/assets/css`. Extract only the needed CSS rules that might be useful for the page(s).

**Comment by Mastaleru** [comment]
https://github.com/PharmaLedger-IMI/clinical-site-ssapp/commit/ef20208a942d9be6d567c9ea606a7c89725f877f
