### ISSUE TITLE
Expose a rest api that returns the adaptor's DID

### ISSUE THREAD

**Issue by elubilu** [PharmaLedger-IMI/iot-pmed-workspace#121]
e.g:  get /iotAdapter/adaptorIdentity

**Comment by Mastaleru** [comment]
Usages:
GET http://localhost:8080/iotAdapter/adaptorIdentity

Request will fulfill with status code 200 and  a message like this:

`{"message":"did:ssi:name:iot:iotAdap3tor33"}`

If an error occurs, status code 500 will be returned.
