### ISSUE TITLE
Add patient code in the Add Trial Participant modal

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/iot-pmed-workspace#123]
The patient code(given by the hospital) is required for the IoT adapter in order to match the correct health data (patientCode, deviceId)

**Comment by nliappas** [comment]
![image](https://user-images.githubusercontent.com/67898132/155116541-7873b7e3-02df-486b-9e21-0ff6b338d4a3.png)

**Comment by nliappas** [comment]
implemented. need to be checked that the number is stored in Trial participant DSU.
