### ISSUE TITLE
[BUG] Strange Behavior after wallet creation (DID related?)

### ISSUE THREAD

**Issue by nliappas** [PharmaLedger-IMI/iot-pmed-workspace#124]
This error does not affect the functionalities for the moment. 

If the user creates a new wallet and immediately opens the SSAPP and stores a DSU the following error appears: 

![image](https://user-images.githubusercontent.com/67898132/155181873-7b4b3d0a-b986-4a3d-8c78-f4fa406beead.png)

And then next time he refreshes the SSAPP this error will always appear:

![image](https://user-images.githubusercontent.com/67898132/155182118-7d36bfd9-de84-4e4b-9cac-92878fb0b57d.png)

This error does not appear when the user creates a new wallet, refreshes the SSAPP and continues working with DSUs. 

To reproduce this behavior: create a new wallet in researcher SSAPP, add a new study (without refreshing or logging out of the wallet), go to the last step that creates the DSU and observe the error.

**Comment by Mastaleru** [comment]
start did-adaptor
