### ISSUE TITLE
View Consents

### ISSUE THREAD

**Issue by nliappas** [PharmaLedger-IMI/iot-pmed-workspace#126]
Main page of Dynamic Consents: includes table

![image](https://user-images.githubusercontent.com/67898132/155296441-ce5266a0-d244-4679-9257-1e9720d07197.png)

**Comment by Mastaleru** [comment]
https://github.com/PharmaLedger-IMI/iot-pmed-workspace/commit/7a7eae72095ca39ed8592a596fa5a8e08f44684d
