### ISSUE TITLE
View Consents - Graphs

### ISSUE THREAD

**Issue by nliappas** [PharmaLedger-IMI/iot-pmed-workspace#127]
![image](https://user-images.githubusercontent.com/67898132/155296859-241bac15-ed69-4b80-b2f6-9cb3174e271a.png)

![image](https://user-images.githubusercontent.com/67898132/155296872-a75e64af-60bd-45ee-8c90-6bcd8fe9d7bd.png)

**Comment by Mastaleru** [comment]
@nliappas/Jose please update the mockup with the  desired graphs. Add a proper explanation on what data should be included.

**Comment by cosmintuca** [comment]
![Capture2](https://user-images.githubusercontent.com/100202792/158633976-4de464f9-b9d2-4b5f-9695-938caf384ebb.PNG)

**Comment by cosmintuca** [comment]
@Mastaleru I have commited the changes for styling(https://github.com/PharmaLedger-IMI/clinical-site-theme/commit/9635ca74167481c7657d1c92f83541024155c3fb)
