### ISSUE TITLE
F-M4-2F Generate Dynamic Permissioning

### ISSUE THREAD

**Issue by nliappas** [PharmaLedger-IMI/iot-pmed-workspace#13]
The Adaptor Generates the dynamic consent according to the Device assignation.

**Comment by nliappas** [comment]
The flow: 

1. The IOT Adaptor has access to the patient data of the device.
2. The patient from the patient SSAPP chooses to share specific data to someone (researcher). 
3. The IOT Adaptor should receive a request to generate a dynamic consent according to the patient's request to donate/share his data. 
4. The IOT Adaptor generates/creates the dynamic consent in a DSU and sharing with the researchers.

@amedranogil Is this correct?? for @elubilu

**Comment by elubilu** [comment]
I think the flow should be like below: 

1. The **IOT Adaptor** has access to the patient data of the device in the main DSU. 
2. The Patient from the **Patient SSApp** chooses to share specific data to someone (researcher). 
3. Then **Patient SSApp** will create a shareable DSU(seedSSI, sReadSSI) with Dynamic Consent. 
4. After that, The **Patient SSApp** share the seedSSI to the **IOT Adaptor** to store specific data based on the Dynamic Consent.
5. Next, The **Patient SSApp** share the sReadSSI to  the **IOT Adaptor**  to expose data API.

**Comment by amedranogil** [comment]
@elubilu is right, the dPermissioning is generated at the Patient SSApp. The IoT Adapter should ensure the Patient SSApp, and the professional SSApp, have access to the patient's data.
however this needs to be configurable, maybe through the assignation, because there are some extended UC which will need this.

**Comment by nliappas** [comment]
ok so @elubilu let's make a graph (like the one you showed me) with this flow, it will be helpful for everyone within UC7-9

**Comment by amedranogil** [comment]
Is this issue deprecated?
@elubilu @raihan2006i
