### ISSUE TITLE
F-M2-4A Write/produce evidence results (UI)

### ISSUE THREAD

**Issue by nliappas** [PharmaLedger-IMI/iot-pmed-workspace#17]
Enabling the researcher to report research results through an UI by API that later can be used with automatic reporters (personalized feedback).

**Comment by elubilu** [comment]
@nliappas @amedranogil Where can i find the Mockup for UI? I have checked both technical documentation and Figma, however I didn't find any mockup or UI for this task.

**Comment by amedranogil** [comment]
There is currently no UI defined for Evidence.
However it should be mapping the data model, providing the researcher the means to fill in the required information.
If you feel you need a Mockup I can ask the team to develop it, but as said it should be very straight forward.

**Comment by elubilu** [comment]
Yes, please develop the mockup. As I need the mockup for implementing the UI.
