### ISSUE TITLE
F-M2-4F list the dPermissions issued

### ISSUE THREAD

**Issue by nliappas** [PharmaLedger-IMI/iot-pmed-workspace#21]
List all the dynamic permission issued by the patient/researchers/users with target the researcher.

**Comment by amedranogil** [comment]
Maybe add some statistics? 
 - temporal graphs of how many dPermissions have been issued by day
 - temporal graphs of how many users have issued a dPersmission by day
 - total data points
 - total users
 - Filter the above by type of data/observation
 - ...
