### ISSUE TITLE
F-M3-2F Data Matchmaking

### ISSUE THREAD

**Issue by nliappas** [PharmaLedger-IMI/iot-pmed-workspace#26]
Receive Information requests and execute the DataMatching function to determine the shareable DSU with the Study.

DSU sharable candidates should go through the dPermision function #30 ; which means some, if not most, candidates could automatically be shared due to eConsent coverage. Other Candidates will be asked individually (so #30 function should be called only when the user accesses the Data shared screen, this is #48 UI, only for the Candidates that are not automatically accepted).

**Comment by elubilu** [comment]
I believe this task depends on #18  which will trigger the Information Request. After Information Request triggered by Investigator SSApp, I believe a Patient must accept the request through Patient SSAapp. Where is the wireframe for that? @nliappas @amedranogil

**Comment by nliappas** [comment]
this should only do the matching between the Information Request and the Patient Data to have the shareable DSU. Does not require UI. The UI you are talking about might be in the notifications of the patient (in the mock up should be in the notifications or something like that but is not there yet; this requires clarifications)

**Comment by elubilu** [comment]
@nliappas Yes, You are right. We need to resolve this issue(mockup) as soon as possible. Because when a patient will accept the information request at that moment the **Patient SSApp** will create the shareable DSU.

**Comment by amedranogil** [comment]
Notification of data matching can be one (or multiple of):
 - push notification
 - task bar notification
 - in app notification (when the user opens the app)
 - in menu notification (when the menu is shown)
 - updated in the UI

**Comment by amedranogil** [comment]
A local database of data & target candidates should be kept, this is the result of Data matchmaking. Parallel to this process dPermissioning (#30) should be called, when the candidate is approved, it is removed from candidate DB, if it is not approved, it means that it needs UI, thus it will remain to be checked by #48 when appropriate (the user will still be notified about the existance of entries in this DB so they access the dPermission managment UI and answer for all pending candidates).
