### ISSUE TITLE
F-M3-3F Share data- e/consent/ dynamic consent (UI for Data Matchmaking)

### ISSUE THREAD

**Issue by nliappas** [PharmaLedger-IMI/iot-pmed-workspace#27]
When users select it: Execute the Donation Action in the Info Request, generating the corresponding dynamic permission DSU.

2 options to notify the user: data matchmaking will be executed when this UI is opened or we send a notification to the patient ssapp.

**Comment by amedranogil** [comment]
duplicate of #30 
At least this is the UI part of #30 .
could overlap #48
