### ISSUE TITLE
F-M5-2A eDiary Management

### ISSUE THREAD

**Issue by nliappas** [PharmaLedger-IMI/iot-pmed-workspace#32]
Report the de use of the chest patch the is connected to the IoT device. The patch can be detached from the patient, change for new ones, etc. These actions should be reported in this diary, as is describe in the trial protocol. e-diary interface: (a) summary of all previous diary entries; (b) Add a new report; (c) Confirmation of new entry.

**Comment by amedranogil** [comment]
eDairy entry is an FHIR HL7 QuestionnaireResponse.
It is stored in a DSU in the patient's wallet,
Sharing with the professional might depend on #2
