### ISSUE TITLE
F-M5-2F Consent check, dPermission generation

### ISSUE THREAD

**Issue by nliappas** [PharmaLedger-IMI/iot-pmed-workspace#34]
Observe the consent status.
There is no UI. 
It is only to check e-consent meaning that allows the ediary to share the information with the professional.

**Comment by anastath** [comment]
Is there a need for the ediary to check the consent status before sharing ediary information with the Professional? Please clarify, since this since in the Architecture slides, this is not mentioned.
![image](https://user-images.githubusercontent.com/31134750/118617312-2e6be880-b7cb-11eb-942d-82a63415844e.png)

**Comment by amedranogil** [comment]
Yes, when ever information is shared between roles the consent needs checking.
In some cases this is managed through dynamic permissioning.

**Comment by amedranogil** [comment]
dynamic permission should check the status of eConsent, at the moment of sharing it should be active, and the dynamic permission should refer (as in DID) to this eConsent, the Target role and the data to be shared (along with other metadata such as current status).

in an advanced version, eConent and the dPermission should be compatible, Thus the function should check that
 1. the eConsent status is active
 2. the eConsent "granted data" for the dPermission target user, is a super set of the dPermission "data to be shared"
if these two are correct, then the dPermision is generated automatically.
I other case this means the system is being asked for additional permissions outside the scope of current usable eConsent, thus a dPermission needs to be generated via a UI to the user, so they explicitly approve the share.

This should be a function, which receives the "Data to be shared" and "target entity to share with" as inputs. The Output should be a dPermission DSU (FIHR [conent](https://www.hl7.org/fhir/consent.html) schema) if applicable (automatic or manual). The function should also post the DSU (data + dPermission) to the target wallet.

**Comment by amedranogil** [comment]
see #30
