### ISSUE TITLE
eDiary PWA Screen size based CSS rules

### ISSUE THREAD

**Issue by irimiacosmin** [PharmaLedger-IMI/iot-pmed-workspace#35]
Screens of the eDiary are made for a PWA, mobile environment but this does not mean that they will adapt properly for every screen. We need to take our time and make proper CSS @media based rules for the most important screen resolutions and devices.

**Comment by Mastaleru** [comment]
handled by bootstrap and CSS flex rules. 

iPad Mini
![image](https://user-images.githubusercontent.com/1469129/151795803-724d5c23-ce25-4d2a-84d4-9f3327583dae.png)

iPhone SE
![image](https://user-images.githubusercontent.com/1469129/151795982-e58d930e-ad45-4744-aefa-b8457f589518.png)

Surface Duo
![image](https://user-images.githubusercontent.com/1469129/151801145-bdf2ab74-be19-4ab3-9b15-e407f41e49ba.png)

Galaxy S8
![image](https://user-images.githubusercontent.com/1469129/151800465-e0172e5c-3b7a-4d8d-aca0-9b3bfaa0258f.png)
![image](https://user-images.githubusercontent.com/1469129/151800530-a99023b9-91fc-4b15-932a-32838817998e.png)
