### ISSUE TITLE
Integration of IoT Device Identification from T3.9

### ISSUE THREAD

**Issue by amedranogil** [PharmaLedger-IMI/iot-pmed-workspace#43]
Use the IMTF features to identify the device.

Open question: 
 - how is the professional going to identify the physical device (on his hand) and assign it to the patient (through the Professional SSApp #2 ) ?
 - The IoT ADaptor should use the IMTF identifyer for the device
 - The user should also be able to identify the device (in cases where more than one device is assigned)

**Comment by nliappas** [comment]
is being implemented in task #121
