### ISSUE TITLE
F-M2-4A-2 Write/produce evidence results (API)

### ISSUE THREAD

**Issue by amedranogil** [PharmaLedger-IMI/iot-pmed-workspace#46]
Providing the function of publishing automatic evidence to EXTERNAL data analytics process.

**Comment by nliappas** [comment]
This function will create a service to post evidence in the existing API  or in a new API.

**Comment by amedranogil** [comment]
The API should be (securely) accessible by external apps, along with frontend. Securely: only authorised external apps by the researcher are allowed to post new evidence results.
The idea of evidence results is that, once the data is processed (see #19 ) and new knowledge is extracted from it, this knowledge can be shared with the rest of researchers, professionals and patients.
Evidence results thus, should be publicly accessible (and findable) by anyone.
Evidence results will contain a reference to a scientific publication, and/or a set of conditions and risks for each. In the latter case Evidence results can be matchmaked to patient information (do the conditions match?) as to inform patients about new found risks thay may affect them.
All evidence results are associated with trials, this way patients can review the outcome of the trials they have participated in, regardless if the new knowledge affects them or not.
