### ISSUE TITLE
F-M1-3F Patient Management – advanced -(general info, etc)

### ISSUE THREAD

**Issue by nliappas** [PharmaLedger-IMI/iot-pmed-workspace#6]
List of participants within the clinical trial. 

Each row  will have these elements: 
 1. participant ID
 2. IoT Device Status
 3. time of last data received from IoT
 4. status of informed consents
 5. access the participant's IoT information ( got to #7 )
 6. edit alert threshholds

**Comment by anastath** [comment]
@amedranogil, @nliappas, @josegterius, could you please provide us with wireframe(s) for this task ?

**Comment by amedranogil** [comment]
we have linked all wireframes for all SSAPPs in the projects page:
https://github.com/PharmaLedger-IMI/iot-pmed-workspace/projects

**Comment by amedranogil** [comment]
The UI is done, the advanced option needs to connect the backend stuff, i.e: The data from the DSUs...

**Comment by amedranogil** [comment]
Proposed reassignment to Romsoft
