### ISSUE TITLE
Identities for IoT Adaptor

### ISSUE THREAD

**Issue by nliappas** [PharmaLedger-IMI/iot-pmed-workspace#69]
Generate identity submodule. Attach a DID to the wallet. Need to confirm who creates the identities.

**Comment by nliappas** [comment]
attach 1 DID and keep it to be used by other ssapps in the communication.

**Comment by Mastaleru** [comment]
DID integration is completed. Maybe a rest api should discover the adaptor's DID. e.g get /iotAdapter/adaptorIdentity
