### ISSUE TITLE
[UI/UX] Implement Trial Management page

### ISSUE THREAD

**Issue by paiusCatalin** [PharmaLedger-IMI/iot-pmed-workspace#87]
**Implementation:**
Provided mock-up: https://www.figma.com/proto/WzlfNehyQjLLLgqPKxncyB/Wireframing?node-id=261514%3A251&scaling=min-zoom
Match Patient/Device button will redirect the user to the Match Patient with Device form page.
Manage Patient button will redirect the user to Patient List page.

_For the design part_, keep in mind to apply the result of #76 task.
_For the HTML part_, keep in mind to follow the guidelines after the refactor for the other pages (e.g. #80, #79, #78...)

**Expected result:**
The page should look like in the provided mock-ups

**Comment by elubilu** [comment]
@paiusCatalin  Where can I find the image in .png format?

**Comment by paiusCatalin** [comment]
Hi @elubilu, 
A new image in SVG format has been added within #102. 
Could you please validate that the new image has better quality also on your side?

Thank you.
