### ISSUE TITLE
[Refactor] [UI/UX] Create a component or a template for the Pharma header and footer

### ISSUE THREAD

**Issue by paiusCatalin** [PharmaLedger-IMI/iot-pmed-workspace#91]
**Current state:**
At this point, the Pharma header and footer are implemented in every HTML file.
![header-footer](https://user-images.githubusercontent.com/17168446/141293378-ed869039-2057-421a-abaf-05bd150cf179.PNG)
![header-footer-html](https://user-images.githubusercontent.com/17168446/141293846-7a6a3d77-d33c-4fc8-a00e-4741f33cee71.PNG)

**Implementation:**
Create a template or a component with the header and footer in order to avoid the duplicate code.
Examples and guidance of custom components defined using webcardinal.
https://github.com/PharmaLedger-IMI/leaflet-ssapp/tree/master/code/components
https://github.com/PharmaLedger-IMI/leaflet-ssapp/tree/master/code/scripts/controllers/components
https://github.com/PharmaLedger-IMI/leaflet-ssapp/blob/master/code/scripts/preload.js

**Comment by oneamanish** [comment]
see my pull req.
